# Generated by Django 4.2.17 on 2024-12-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_supervisor_groups_supervisor_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('hospital', 'Hospital')], default='supervisor', max_length=20),
        ),
    ]
