# Generated by Django 4.2.17 on 2024-12-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_sex', models.CharField(max_length=10)),
                ('patient_blood_type', models.CharField(max_length=3)),
                ('patient_status', models.CharField(choices=[('recovered', 'Recovered'), ('deceased', 'Deceased'), ('under_treatment', 'Under Treatment')], max_length=20)),
                ('main_symptom_causing_death', models.CharField(blank=True, max_length=255, null=True)),
                ('alive', models.BooleanField(default=True)),
                ('season', models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn')], max_length=10)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.disease')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
