# Generated by Django 4.2.17 on 2025-01-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='patient_number',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('hospital', 'patient_number'), name='unique_patient_number_per_hospital'),
        ),
    ]
