# Generated by Django 4.2.17 on 2024-12-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_user'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='hospital',
            #name='user',
        #),
    ]
