# Generated by Django 4.2.17 on 2024-12-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_hospital_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='username',
            new_name='email',
        )#,
        #migrations.RemoveField(
           # model_name='hospital',
            #name='user',
        #),
    ]
