# Generated by Django 4.2.17 on 2024-12-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_rename_username_hospital_email_remove_hospital_user'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='hospital',
            #name='user',
        #),
    ]
