# Generated by Django 4.2.17 on 2025-01-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_hospital_user_hospital_last_login'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='hospital',
            #name='user',
        #),
        migrations.CreateModel(
            name='HospitalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
