# Generated by Django 4.2.17 on 2025-01-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_hospital_user_hospitaltoken'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='hospital',
            #name='user',
        #),
    ]
